# Generated by Django 4.1.4 on 2022-12-14 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_country_options_alter_show_alt_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
