# Generated by Django 4.1.4 on 2022-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_show_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='show_category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='show',
            name='episodes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
