# Generated by Django 4.1.4 on 2022-12-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_rename_show_category_show_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='finale_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
