# Generated by Django 4.1.4 on 2022-12-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_show_finale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showperson',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_people', to='shows.show'),
        ),
    ]
