# Generated by Django 4.1.4 on 2022-12-15 20:41

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_alter_showperson_person_alter_country_table_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='usershowrating',
            trigger=pgtrigger.compiler.Trigger(name='update_show_rating_on_rate_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                DELETE FROM \n                    user_show_rating\n                WHERE\n                    show_id = NEW.show_id and user_id = NEW.user_id;\n                \n                UPDATE show\n                SET\n                    times_rated = times_rated + 1,\n                    ratings_sum = ratings_sum + NEW.rating,\n                    rating = (ratings_sum + NEW.rating) / (times_rated + 1)\n                WHERE\n                    id = NEW.show_id;\n                RETURN NEW;\n                ', hash='bb51e7ff5757f085b322bb5a24659bbb93e06957', operation='INSERT', pgid='pgtrigger_update_show_rating_on_rate_insert_7d690', table='user_show_rating', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usershowrating',
            trigger=pgtrigger.compiler.Trigger(name='update_show_rating_on_rate_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                UPDATE show\n                SET\n                    times_rated = times_rated - 1,\n                    ratings_sum = ratings_sum - OLD.rating,\n                    rating = (ratings_sum - OLD.rating) / GREATEST(times_rated - 1, 1)\n                WHERE\n                    id = OLD.show_id;\n                RETURN OLD;\n                ', hash='afd06fd03ab89770ed87d912fc7d7a41339d4124', operation='DELETE', pgid='pgtrigger_update_show_rating_on_rate_delete_26dab', table='user_show_rating', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usershowrating',
            trigger=pgtrigger.compiler.Trigger(name='update_show_rating_on_rate_edit', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                UPDATE show\n                SET\n                    ratings_sum = ratings_sum - OLD.rating + NEW.rating,\n                    rating = (ratings_sum - OLD.rating + NEW.rating) / times_rated\n                WHERE\n                    id = OLD.show_id;\n                RETURN NEW;\n                ', hash='81a16149fb7084e40455d5a88793cdd6adb40726', operation='UPDATE', pgid='pgtrigger_update_show_rating_on_rate_edit_d2f0e', table='user_show_rating', when='AFTER')),
        ),
    ]
