# Generated by Django 4.1.4 on 2022-12-15 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_usershowrating_update_show_rating_on_rate_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershowrating',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, "Rating can't be below 1."), django.core.validators.MaxValueValidator(10, "Rating can't be above 10.")]),
        ),
    ]
