# Generated by Django 4.1.4 on 2022-12-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_alter_usershowrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_category',
            new_name='category',
        ),
    ]
