# Generated by Django 4.1.4 on 2022-12-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_alter_genre_category_alter_show_age_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='age_rating',
            field=models.IntegerField(choices=[(1, '0+'), (2, '10+'), (3, '13+'), (4, '16+'), (5, '18+')], db_index=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.IntegerField(choices=[(1, 'Movie'), (2, 'TV Show'), (3, 'Cartoon'), (4, 'Anime')], db_index=True),
        ),
    ]
