# Generated by Django 4.1.4 on 2022-12-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_alter_show_age_rating_alter_show_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showperson',
            name='person_type',
            field=models.IntegerField(choices=[(1, 'Producer'), (2, 'Actor')]),
        ),
    ]
