# Generated by Django 4.1.4 on 2022-12-21 02:58

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0015_alter_show_rating'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='usershowrating',
            name='update_show_rating_on_rate_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usershowrating',
            name='update_show_rating_on_rate_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usershowrating',
            name='update_show_rating_on_rate_edit',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usershowrating',
            trigger=pgtrigger.compiler.Trigger(name='update_show_rating_on_rate_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                DELETE FROM \n                    user_show_rating\n                WHERE\n                    show_id = NEW.show_id and user_id = NEW.user_id;\n                \n                UPDATE show\n                SET\n                    times_rated = times_rated + 1,\n                    ratings_sum = ratings_sum + NEW.rating,\n                    rating = (ratings_sum + NEW.rating)::decimal / (times_rated + 1)\n                WHERE\n                    id = NEW.show_id;\n                RETURN NEW;\n                ', hash='c4f644d5a153364ba93d75c27ab3da9732ba9f22', operation='INSERT', pgid='pgtrigger_update_show_rating_on_rate_insert_7d690', table='user_show_rating', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usershowrating',
            trigger=pgtrigger.compiler.Trigger(name='update_show_rating_on_rate_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                UPDATE show\n                SET\n                    times_rated = times_rated - 1,\n                    ratings_sum = ratings_sum - OLD.rating,\n                    rating = (ratings_sum - OLD.rating)::decimal / GREATEST(times_rated - 1, 1)\n                WHERE\n                    id = OLD.show_id;\n                RETURN OLD;\n                ', hash='7a60c870399b06c5be4c056646dbcadea71e9e93', operation='DELETE', pgid='pgtrigger_update_show_rating_on_rate_delete_26dab', table='user_show_rating', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usershowrating',
            trigger=pgtrigger.compiler.Trigger(name='update_show_rating_on_rate_edit', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                UPDATE show\n                SET\n                    ratings_sum = ratings_sum - OLD.rating + NEW.rating,\n                    rating = (ratings_sum - OLD.rating + NEW.rating)::decimal / times_rated\n                WHERE\n                    id = OLD.show_id;\n                RETURN NEW;\n                ', hash='08e040c04569577c6b6f40c80b6cb524f60a5386', operation='UPDATE', pgid='pgtrigger_update_show_rating_on_rate_edit_d2f0e', table='user_show_rating', when='AFTER')),
        ),
    ]
