# Generated by Django 4.1.4 on 2022-12-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0017_alter_genre_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rating',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
