# Generated by Django 4.1.4 on 2022-12-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0019_alter_showperson_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('name', 'category')},
        ),
    ]
