# Generated by Django 4.1.4 on 2022-12-14 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListShow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('list_type', models.CharField(choices=[('watching', 'Watching'), ('plan_to_watch', 'Plan to Watch'), ('completed', 'Completed'), ('dropped', 'Dropped')], db_index=True, max_length=13)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to='shows.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows_in_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
