# Generated by Django 4.1.4 on 2022-12-15 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_listshow_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='listshow',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
