# Generated by Django 4.1.4 on 2022-12-15 21:48

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_alter_listshow_list_type'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='listshow',
            trigger=pgtrigger.compiler.Trigger(name='delete_list_show_on_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                DELETE FROM \n                    list_show\n                WHERE\n                    show_id = NEW.show_id and \n                    user_id = NEW.user_id and\n                    list_type = OLD.list_type;\n                return NEW;\n                ', hash='222ed9481334d396ba649499fd0c9b7c31d4b3f6', operation='INSERT', pgid='pgtrigger_delete_list_show_on_insert_f6159', table='list_show', when='AFTER')),
        ),
    ]
