# Generated by Django 4.1.4 on 2022-12-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_listshow_delete_list_show_on_insert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listshow',
            name='list_type',
            field=models.IntegerField(choices=[(1, 'Watching'), (2, 'Plan to Watch'), (3, 'Finished'), (4, 'Dropped')]),
        ),
    ]
