# Generated by Django 4.1.4 on 2022-12-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='commentvote',
            table='comment_vote',
        ),
    ]
