# Generated by Django 4.1.4 on 2022-12-17 15:10

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_remove_comment_reply_to_comment_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='commentvote',
            trigger=pgtrigger.compiler.Trigger(name='update_comment_likes_on_new_vote', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                DELETE FROM \n                    comment_vote\n                WHERE\n                    comment_id = NEW.comment_id and user_id = NEW.user_id;\n\n                UPDATE comment\n                SET\n                    likes = likes + NEW.vote\n                WHERE\n                    id = NEW.comment_id;\n                RETURN NEW;\n                ', hash='ada90e781d449a586b9991e0cde2de036ebc34b6', operation='INSERT', pgid='pgtrigger_update_comment_likes_on_new_vote_9b6eb', table='comment_vote', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='commentvote',
            trigger=pgtrigger.compiler.Trigger(name='update_comment_likes_on_vote_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                UPDATE comment\n                SET\n                    likes = likes - OLD.vote\n                WHERE\n                    id = OLD.comment_id;\n                RETURN OLD;\n                ', hash='4c5e657658c9ec73d9430a59988965910bf18f37', operation='DELETE', pgid='pgtrigger_update_comment_likes_on_vote_delete_305cf', table='comment_vote', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='commentvote',
            trigger=pgtrigger.compiler.Trigger(name='update_comment_likes_on_vote_edit', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                UPDATE comment\n                SET\n                    likes = likes - OLD.vote + NEW.vote\n                WHERE\n                    id = OLD.comment_id;\n                RETURN NEW;\n                ', hash='be70276de0cad47f48910545a37d0dc33d4216ff', operation='UPDATE', pgid='pgtrigger_update_comment_likes_on_vote_edit_1808a', table='comment_vote', when='AFTER')),
        ),
    ]
