# Generated by Django 4.1.4 on 2022-12-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0019_alter_showperson_person_type'),
        ('comments', '0006_commentvote_update_comment_likes_on_new_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shows.show'),
        ),
    ]
