# Generated by Django 4.1.4 on 2022-12-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/%Y/%m/%d/'),
        ),
    ]
